-- Taoj bang Category
CREATE TABLE Category (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name NVARCHAR2(255),
    Status NUMBER
);

-- T?o b?ng Product
CREATE TABLE Product (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name NVARCHAR2(255),
    Price NUMBER,
    Status NUMBER,
    CategoryId NUMBER,
    CreateDate TIMESTAMP,
    FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);

-- them category
INSERT INTO Category VALUES (1, 'Sach', 1);
INSERT INTO Category VALUES (2, 'Quan ao', 0);
INSERT INTO Category VALUES (3, 'Do gia dung', 1);

SELECT * FROM Category; 

-- them sp
INSERT INTO Product VALUES (1, 'John Doe', 500, 0, 1, '');
INSERT INTO Product VALUES (2, 'John lala', 900, 1, 3, '');
INSERT INTO Product VALUES (3, 'Mimi Doe', 300, 0, 2, '');

SELECT * FROM Product; 

DECLARE
    myCursor SYS_REFCURSOR;
BEGIN
    Sp_getallproduct(categoryId => 1, result => myCursor);
    -- Process the result set using the cursor variable
    -- (e.g., use a loop to fetch rows from the cursor)
END;
-- T?o Stored Procedure Sp_getallproduct
CREATE OR REPLACE PROCEDURE Sp_getallproduct (
    categoryId IN NUMBER
) AS
BEGIN
        SELECT * FROM Product WHERE CategoryId = categoryId;
END Sp_getallproduct;


EXEC Sp_getallproduct(2);

DROP TABLE students;
